import {
	IUserState,
	IProfileCard,
	ICodeSaves,
	ICodeSavesArr,
	IEducation,
	IEducationArr,
	IExperience,
	IExperienceArr,
	ICompletedChapter,
	ICompletedChapterArr,
	IEnrolledCourses,
	IEnrolledCoursesArr,
	IQuizScore,
	IQuizScoreArr,
} from "./profileInterfaces";
import { IEditableInput } from "./EditableTextInterface";
import {
	ICoursesListItem,
	ICoursesList,
	ICourse,
	ICourseChapter,
	ICourseChapterArr,
	ICourseChapterQuiz,
	ICourseChapterQuizArr,
	IQuizAnswer,
} from "./coursesInterfaces";

import { IPostsArr, IComment, ICommentsArr, IPost } from "./postsInterfaces";
import { IProblem, IProblemArr } from "./dashboardInterfaces";
export type {
	IUserState,
	IEditableInput,
	IProfileCard,
	ICoursesListItem,
	ICoursesList,
	ICourseChapter,
	ICourse,
	ICourseChapterArr,
	ICourseChapterQuiz,
	ICourseChapterQuizArr,
	IQuizAnswer,
	ICodeSaves,
	ICodeSavesArr,
	ICompletedChapter,
	ICompletedChapterArr,
	IEducation,
	IEducationArr,
	IEnrolledCourses,
	IEnrolledCoursesArr,
	IExperience,
	IExperienceArr,
	IQuizScore,
	IQuizScoreArr,
	IComment,
	ICommentsArr,
	IPost,
	IPostsArr,
	IProblem,
	IProblemArr,
};
