export const LOGO = "wtl.";
export const COMMUNITY = "Community";
export const ABOUT = "About";
export const CONSOLE = "Console";
export const LEARNING_PATH = "LearningPath";
export const LOGIN = "Login";
export const REGISTER = "Register";
export const OPEN = "open";
export const TOKEN = "TOKEN";
export const YUP_EMPTY_USERNAME = "Username can't be empty!";
export const YUP_VALID_EMAIL = "Provide a valid email!";
export const YUP_EMPTY_EMAIL = "Email can't be empty!";
export const YUP_EMPTY_PASSWORD = "Password can't be empty!";
export const YUP_VALID_PASSWORD = "min 6 length = 0-9,a-z,A-Z and specials";
export const YUP_MATCH_RE_PASSWORD = "Password must match!";
export const YUP_EMPTY_RE_PASSWORD = "Re-Password can't be empty!";
export const COULD_NOT_REGISTER = "Could not register!";
