export const randomFactsArr = [
	"86% of visitors want info about prosucts/service on the hompage.",
	"The most popular language by far on the internet is English. Over 25.3% of the internet is in English, 19.8% is in Chinese, and 8% is in Spanish.",
	"98-99% of people have the internet in Denmark, Iceland, the UAE, Kuwait, and Qatar.",
	"The Chrome web browser is used by 65.9% of internet users worldwide.",
	"Mobile traffic to websites is over 51% of total online traffic.",
	"49. 370.1 million, the total number of domain names in the world in 2020.",
	"Almost half (43.8%) of the total number of domains are .com and .net.",
	"The first-ever website was launched on August 6th, 1991. The developer behind it was a CERN employee, Tim Berners Lee. The site was about his World Wide Web project. ",
	"More than half of digital ad investments are captured by Google and Facebook",
	"Hackers, scammers, and other malicious individuals around the web attack persons, websites, and businesses every 39 seconds.",
	"Electronic mail, better known as email, was developed in 1971 by Ray Tomlinson, who invented a new way to use the internet.",
	"ARPANET, the modern internet's predecessor, adapted the TCP/IP system on January 1st, 1983, thus creating the modern-day internet.",
	"The first widely used web browser, Mosaic, was released in 1993.",
	"As of 2020, more than 500 hours of video are uploaded to YouTube every minute.",
];
