//ALERT
export enum AlertActionTypes {
	SET_ALERT = "SET_ALERT",
	REMOVE_ALERT = "REMOVE_ALERT",
}

//AUTH
export enum AuthActionTypes {
	REGISTER_SUCCESS = "REGISTER_SUCCESS",
	REGISTER_FAIL = "REGISTER_FAIL",
	USER_LOADED = "USER_LOADED",
	AUTH_ERROR = "AUTH_ERROR",
	LOGIN_FAIL = "LOGIN_FAIL",
	LOGIN_SUCCESS = "LOGIN_SUCCESS",
	LOGOUT = "LOGOUT",
	CLEAR_PROFILE = "CLEAR_PROFILE",
}
